import { initContract } from "@ts-rest/core";
import {
  AgentsSendMessageRequestSchema,
  AgentsUiInterruptResponseSchema,
  AgentsUiSendMessageResponseSchema,
  AgentsUiWorktreeConversationResponseSchema,
  AgentListResponseSchema,
  AgentResponseSchema,
  AppConfigSchema,
  AvailableBranchesQuerySchema,
  BranchListResponseSchema,
  CiLogsResponseSchema,
  CreateWorktreeRequestSchema,
  CreateWorktreeResponseSchema,
  EnabledResponseSchema,
  ErrorResponseSchema,
  OkResponseSchema,
  ProjectSnapshotSchema,
  PullMainRequestSchema,
  PullMainResponseSchema,
  UpsertCustomAgentRequestSchema,
  ValidateCustomAgentResponseSchema,
  SendWorktreePromptRequestSchema,
  SetWorktreeArchivedRequestSchema,
  SetWorktreeArchivedResponseSchema,
  ToggleEnabledRequestSchema,
  WorktreeDiffResponseSchema,
  WorktreeListResponseSchema,
  LinearIssuesResponseSchema,
  ExternalTmuxSessionListResponseSchema,
  ScratchSessionListResponseSchema,
  CreateScratchSessionRequestSchema,
  CreateScratchSessionResponseSchema,
  ProjectIdParamsSchema,
  ProjectScopedWorktreeNameParamsSchema,
  ProjectScopedScratchIdParamsSchema,
  ExternalSessionNameParamsSchema,
  ProjectListResponseSchema,
  CreateProjectRequestSchema,
  CreateProjectResponseSchema,
  RemoveProjectRequestSchema,
  OpenWorktreeRequestSchema,
  UpdateWorktreeRequestSchema,
} from "./schemas";
import { z } from "zod";

const c = initContract();

export const apiPaths = {
  fetchConfig: "/api/config",
  fetchExternalSessions: "/api/external-sessions",
  fetchProjects: "/api/projects",
  createProject: "/api/projects",
  removeProject: "/api/projects/:projectId",
  fetchAvailableBranches: "/api/projects/:projectId/branches",
  fetchBaseBranches: "/api/projects/:projectId/base-branches",
  fetchProject: "/api/projects/:projectId/project",
  fetchAgents: "/api/projects/:projectId/agents",
  createAgent: "/api/projects/:projectId/agents",
  updateAgent: "/api/projects/:projectId/agents/:id",
  deleteAgent: "/api/projects/:projectId/agents/:id",
  validateAgent: "/api/projects/:projectId/agents/validate",
  attachAgentsWorktreeConversation: "/api/projects/:projectId/agents/worktrees/:name/attach",
  fetchAgentsWorktreeConversationHistory: "/api/projects/:projectId/agents/worktrees/:name/history",
  sendAgentsWorktreeConversationMessage: "/api/projects/:projectId/agents/worktrees/:name/messages",
  interruptAgentsWorktreeConversation: "/api/projects/:projectId/agents/worktrees/:name/interrupt",
  streamAgentsWorktreeConversation: "/ws/projects/:projectId/agents/worktrees/:name",
  fetchWorktrees: "/api/projects/:projectId/worktrees",
  createWorktree: "/api/projects/:projectId/worktrees",
  removeWorktree: "/api/projects/:projectId/worktrees/:name",
  updateWorktree: "/api/projects/:projectId/worktrees/:name",
  openWorktree: "/api/projects/:projectId/worktrees/:name/open",
  closeWorktree: "/api/projects/:projectId/worktrees/:name/close",
  setWorktreeArchived: "/api/projects/:projectId/worktrees/:name/archive",
  sendWorktreePrompt: "/api/projects/:projectId/worktrees/:name/send",
  mergeWorktree: "/api/projects/:projectId/worktrees/:name/merge",
  fetchWorktreeDiff: "/api/projects/:projectId/worktrees/:name/diff",
  fetchLinearIssues: "/api/projects/:projectId/linear/issues",
  setLinearAutoCreate: "/api/projects/:projectId/linear/auto-create",
  setAutoRemoveOnMerge: "/api/projects/:projectId/github/auto-remove-on-merge",
  pullMain: "/api/projects/:projectId/pull-main",
  fetchCiLogs: "/api/projects/:projectId/ci-logs/:runId",
  dismissNotification: "/api/projects/:projectId/notifications/:id/dismiss",
  fetchScratchSessions: "/api/projects/:projectId/scratch-sessions",
  createScratchSession: "/api/projects/:projectId/scratch-sessions",
  removeScratchSession: "/api/projects/:projectId/scratch-sessions/:id",
  attachAgentsScratchConversation: "/api/projects/:projectId/scratch-sessions/:id/agent/attach",
  fetchAgentsScratchConversationHistory: "/api/projects/:projectId/scratch-sessions/:id/agent/history",
  sendAgentsScratchConversationMessage: "/api/projects/:projectId/scratch-sessions/:id/agent/messages",
  interruptAgentsScratchConversation: "/api/projects/:projectId/scratch-sessions/:id/agent/interrupt",
  streamAgentsScratchConversation: "/ws/projects/:projectId/scratch-sessions/:id/agent",
  attachAgentsExternalConversation: "/api/external-sessions/:name/agent/attach",
  fetchAgentsExternalConversationHistory: "/api/external-sessions/:name/agent/history",
  sendAgentsExternalConversationMessage: "/api/external-sessions/:name/agent/messages",
  interruptAgentsExternalConversation: "/api/external-sessions/:name/agent/interrupt",
  streamAgentsExternalConversation: "/ws/external-sessions/:name/agent",
} as const;

const commonErrorResponses = {
  400: ErrorResponseSchema,
  404: ErrorResponseSchema,
  409: ErrorResponseSchema,
  422: ErrorResponseSchema,
  500: ErrorResponseSchema,
  502: ErrorResponseSchema,
  503: ErrorResponseSchema,
} as const;

export const apiContract = c.router({
  fetchConfig: {
    method: "GET",
    path: apiPaths.fetchConfig,
    query: z.object({ projectId: z.string().optional() }).optional(),
    responses: {
      200: AppConfigSchema,
    },
  },
  fetchExternalSessions: {
    method: "GET",
    path: apiPaths.fetchExternalSessions,
    responses: {
      200: ExternalTmuxSessionListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchProjects: {
    method: "GET",
    path: apiPaths.fetchProjects,
    responses: {
      200: ProjectListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  createProject: {
    method: "POST",
    path: apiPaths.createProject,
    body: CreateProjectRequestSchema,
    responses: {
      201: CreateProjectResponseSchema,
      ...commonErrorResponses,
    },
  },
  removeProject: {
    method: "DELETE",
    path: apiPaths.removeProject,
    pathParams: ProjectIdParamsSchema,
    body: RemoveProjectRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchAvailableBranches: {
    method: "GET",
    path: apiPaths.fetchAvailableBranches,
    pathParams: ProjectIdParamsSchema,
    query: AvailableBranchesQuerySchema,
    responses: {
      200: BranchListResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchBaseBranches: {
    method: "GET",
    path: apiPaths.fetchBaseBranches,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: BranchListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchProject: {
    method: "GET",
    path: apiPaths.fetchProject,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: ProjectSnapshotSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  fetchAgents: {
    method: "GET",
    path: apiPaths.fetchAgents,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: AgentListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  createAgent: {
    method: "POST",
    path: apiPaths.createAgent,
    pathParams: ProjectIdParamsSchema,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: AgentResponseSchema,
      400: ErrorResponseSchema,
      409: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  updateAgent: {
    method: "PUT",
    path: apiPaths.updateAgent,
    pathParams: z.object({ projectId: z.string().min(1), id: z.string().min(1) }),
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: AgentResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  deleteAgent: {
    method: "DELETE",
    path: apiPaths.deleteAgent,
    pathParams: z.object({ projectId: z.string().min(1), id: z.string().min(1) }),
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  validateAgent: {
    method: "POST",
    path: apiPaths.validateAgent,
    pathParams: ProjectIdParamsSchema,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: ValidateCustomAgentResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  attachAgentsWorktreeConversation: {
    method: "POST",
    path: apiPaths.attachAgentsWorktreeConversation,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchAgentsWorktreeConversationHistory: {
    method: "GET",
    path: apiPaths.fetchAgentsWorktreeConversationHistory,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendAgentsWorktreeConversationMessage: {
    method: "POST",
    path: apiPaths.sendAgentsWorktreeConversationMessage,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: AgentsSendMessageRequestSchema,
    responses: {
      200: AgentsUiSendMessageResponseSchema,
      ...commonErrorResponses,
    },
  },
  interruptAgentsWorktreeConversation: {
    method: "POST",
    path: apiPaths.interruptAgentsWorktreeConversation,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiInterruptResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchWorktrees: {
    method: "GET",
    path: apiPaths.fetchWorktrees,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: WorktreeListResponseSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  createWorktree: {
    method: "POST",
    path: apiPaths.createWorktree,
    pathParams: ProjectIdParamsSchema,
    body: CreateWorktreeRequestSchema,
    responses: {
      201: CreateWorktreeResponseSchema,
      ...commonErrorResponses,
    },
  },
  removeWorktree: {
    method: "DELETE",
    path: apiPaths.removeWorktree,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  updateWorktree: {
    method: "PATCH",
    path: apiPaths.updateWorktree,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: UpdateWorktreeRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  openWorktree: {
    method: "POST",
    path: apiPaths.openWorktree,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: OpenWorktreeRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  closeWorktree: {
    method: "POST",
    path: apiPaths.closeWorktree,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  setWorktreeArchived: {
    method: "PUT",
    path: apiPaths.setWorktreeArchived,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: SetWorktreeArchivedRequestSchema,
    responses: {
      200: SetWorktreeArchivedResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendWorktreePrompt: {
    method: "POST",
    path: apiPaths.sendWorktreePrompt,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: SendWorktreePromptRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  mergeWorktree: {
    method: "POST",
    path: apiPaths.mergeWorktree,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchWorktreeDiff: {
    method: "GET",
    path: apiPaths.fetchWorktreeDiff,
    pathParams: ProjectScopedWorktreeNameParamsSchema,
    responses: {
      200: WorktreeDiffResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchLinearIssues: {
    method: "GET",
    path: apiPaths.fetchLinearIssues,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: LinearIssuesResponseSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  setLinearAutoCreate: {
    method: "PUT",
    path: apiPaths.setLinearAutoCreate,
    pathParams: ProjectIdParamsSchema,
    body: ToggleEnabledRequestSchema,
    responses: {
      200: EnabledResponseSchema,
      ...commonErrorResponses,
    },
  },
  setAutoRemoveOnMerge: {
    method: "PUT",
    path: apiPaths.setAutoRemoveOnMerge,
    pathParams: ProjectIdParamsSchema,
    body: ToggleEnabledRequestSchema,
    responses: {
      200: EnabledResponseSchema,
      ...commonErrorResponses,
    },
  },
  pullMain: {
    method: "POST",
    path: apiPaths.pullMain,
    pathParams: ProjectIdParamsSchema,
    body: PullMainRequestSchema,
    responses: {
      200: PullMainResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchCiLogs: {
    method: "GET",
    path: apiPaths.fetchCiLogs,
    pathParams: z.object({ projectId: z.string().min(1), runId: z.union([z.number().int().nonnegative(), z.string().regex(/^\d+$/).transform((value) => Number(value))]) }),
    responses: {
      200: CiLogsResponseSchema,
      ...commonErrorResponses,
    },
  },
  dismissNotification: {
    method: "POST",
    path: apiPaths.dismissNotification,
    pathParams: z.object({ projectId: z.string().min(1), id: z.union([z.number().int().nonnegative(), z.string().regex(/^\d+$/).transform((value) => Number(value))]) }),
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
  },
  fetchScratchSessions: {
    method: "GET",
    path: apiPaths.fetchScratchSessions,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: ScratchSessionListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  createScratchSession: {
    method: "POST",
    path: apiPaths.createScratchSession,
    pathParams: ProjectIdParamsSchema,
    body: CreateScratchSessionRequestSchema,
    responses: {
      201: CreateScratchSessionResponseSchema,
      ...commonErrorResponses,
    },
  },
  removeScratchSession: {
    method: "DELETE",
    path: apiPaths.removeScratchSession,
    pathParams: ProjectScopedScratchIdParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  attachAgentsScratchConversation: {
    method: "POST",
    path: apiPaths.attachAgentsScratchConversation,
    pathParams: ProjectScopedScratchIdParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchAgentsScratchConversationHistory: {
    method: "GET",
    path: apiPaths.fetchAgentsScratchConversationHistory,
    pathParams: ProjectScopedScratchIdParamsSchema,
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendAgentsScratchConversationMessage: {
    method: "POST",
    path: apiPaths.sendAgentsScratchConversationMessage,
    pathParams: ProjectScopedScratchIdParamsSchema,
    body: AgentsSendMessageRequestSchema,
    responses: {
      200: AgentsUiSendMessageResponseSchema,
      ...commonErrorResponses,
    },
  },
  interruptAgentsScratchConversation: {
    method: "POST",
    path: apiPaths.interruptAgentsScratchConversation,
    pathParams: ProjectScopedScratchIdParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiInterruptResponseSchema,
      ...commonErrorResponses,
    },
  },
  attachAgentsExternalConversation: {
    method: "POST",
    path: apiPaths.attachAgentsExternalConversation,
    pathParams: ExternalSessionNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchAgentsExternalConversationHistory: {
    method: "GET",
    path: apiPaths.fetchAgentsExternalConversationHistory,
    pathParams: ExternalSessionNameParamsSchema,
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendAgentsExternalConversationMessage: {
    method: "POST",
    path: apiPaths.sendAgentsExternalConversationMessage,
    pathParams: ExternalSessionNameParamsSchema,
    body: AgentsSendMessageRequestSchema,
    responses: {
      200: AgentsUiSendMessageResponseSchema,
      ...commonErrorResponses,
    },
  },
  interruptAgentsExternalConversation: {
    method: "POST",
    path: apiPaths.interruptAgentsExternalConversation,
    pathParams: ExternalSessionNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiInterruptResponseSchema,
      ...commonErrorResponses,
    },
  },
}, {
  strictStatusCodes: true,
});
